# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/framework

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/framework

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/framework/CMakeFiles /root/framework/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/framework/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named router

# Build rule for target.
router: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 router
.PHONY : router

# fast build rule for target.
router/fast:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/build
.PHONY : router/fast

#=============================================================================
# Target rules for targets named fwd

# Build rule for target.
fwd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fwd
.PHONY : fwd

# fast build rule for target.
fwd/fast:
	$(MAKE) -f CMakeFiles/fwd.dir/build.make CMakeFiles/fwd.dir/build
.PHONY : fwd/fast

#=============================================================================
# Target rules for targets named table-test

# Build rule for target.
table-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 table-test
.PHONY : table-test

# fast build rule for target.
table-test/fast:
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/build
.PHONY : table-test/fast

dpdk_init.o: dpdk_init.c.o

.PHONY : dpdk_init.o

# target to build an object file
dpdk_init.c.o:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/dpdk_init.c.o
	$(MAKE) -f CMakeFiles/fwd.dir/build.make CMakeFiles/fwd.dir/dpdk_init.c.o
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/dpdk_init.c.o
.PHONY : dpdk_init.c.o

dpdk_init.i: dpdk_init.c.i

.PHONY : dpdk_init.i

# target to preprocess a source file
dpdk_init.c.i:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/dpdk_init.c.i
	$(MAKE) -f CMakeFiles/fwd.dir/build.make CMakeFiles/fwd.dir/dpdk_init.c.i
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/dpdk_init.c.i
.PHONY : dpdk_init.c.i

dpdk_init.s: dpdk_init.c.s

.PHONY : dpdk_init.s

# target to generate assembly for a file
dpdk_init.c.s:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/dpdk_init.c.s
	$(MAKE) -f CMakeFiles/fwd.dir/build.make CMakeFiles/fwd.dir/dpdk_init.c.s
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/dpdk_init.c.s
.PHONY : dpdk_init.c.s

dummy_routing_table.o: dummy_routing_table.c.o

.PHONY : dummy_routing_table.o

# target to build an object file
dummy_routing_table.c.o:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/dummy_routing_table.c.o
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/dummy_routing_table.c.o
.PHONY : dummy_routing_table.c.o

dummy_routing_table.i: dummy_routing_table.c.i

.PHONY : dummy_routing_table.i

# target to preprocess a source file
dummy_routing_table.c.i:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/dummy_routing_table.c.i
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/dummy_routing_table.c.i
.PHONY : dummy_routing_table.c.i

dummy_routing_table.s: dummy_routing_table.c.s

.PHONY : dummy_routing_table.s

# target to generate assembly for a file
dummy_routing_table.c.s:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/dummy_routing_table.c.s
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/dummy_routing_table.c.s
.PHONY : dummy_routing_table.c.s

forwarder/fwd.o: forwarder/fwd.c.o

.PHONY : forwarder/fwd.o

# target to build an object file
forwarder/fwd.c.o:
	$(MAKE) -f CMakeFiles/fwd.dir/build.make CMakeFiles/fwd.dir/forwarder/fwd.c.o
.PHONY : forwarder/fwd.c.o

forwarder/fwd.i: forwarder/fwd.c.i

.PHONY : forwarder/fwd.i

# target to preprocess a source file
forwarder/fwd.c.i:
	$(MAKE) -f CMakeFiles/fwd.dir/build.make CMakeFiles/fwd.dir/forwarder/fwd.c.i
.PHONY : forwarder/fwd.c.i

forwarder/fwd.s: forwarder/fwd.c.s

.PHONY : forwarder/fwd.s

# target to generate assembly for a file
forwarder/fwd.c.s:
	$(MAKE) -f CMakeFiles/fwd.dir/build.make CMakeFiles/fwd.dir/forwarder/fwd.c.s
.PHONY : forwarder/fwd.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/main.c.s
.PHONY : main.c.s

router.o: router.c.o

.PHONY : router.o

# target to build an object file
router.c.o:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/router.c.o
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/router.c.o
.PHONY : router.c.o

router.i: router.c.i

.PHONY : router.i

# target to preprocess a source file
router.c.i:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/router.c.i
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/router.c.i
.PHONY : router.c.i

router.s: router.c.s

.PHONY : router.s

# target to generate assembly for a file
router.c.s:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/router.c.s
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/router.c.s
.PHONY : router.c.s

routing_table.o: routing_table.c.o

.PHONY : routing_table.o

# target to build an object file
routing_table.c.o:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/routing_table.c.o
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/routing_table.c.o
.PHONY : routing_table.c.o

routing_table.i: routing_table.c.i

.PHONY : routing_table.i

# target to preprocess a source file
routing_table.c.i:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/routing_table.c.i
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/routing_table.c.i
.PHONY : routing_table.c.i

routing_table.s: routing_table.c.s

.PHONY : routing_table.s

# target to generate assembly for a file
routing_table.c.s:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/routing_table.c.s
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/routing_table.c.s
.PHONY : routing_table.c.s

test/test.o: test/test.cc.o

.PHONY : test/test.o

# target to build an object file
test/test.cc.o:
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/test/test.cc.o
.PHONY : test/test.cc.o

test/test.i: test/test.cc.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cc.i:
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/test/test.cc.i
.PHONY : test/test.cc.i

test/test.s: test/test.cc.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cc.s:
	$(MAKE) -f CMakeFiles/table-test.dir/build.make CMakeFiles/table-test.dir/test/test.cc.s
.PHONY : test/test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... router"
	@echo "... fwd"
	@echo "... table-test"
	@echo "... edit_cache"
	@echo "... dpdk_init.o"
	@echo "... dpdk_init.i"
	@echo "... dpdk_init.s"
	@echo "... dummy_routing_table.o"
	@echo "... dummy_routing_table.i"
	@echo "... dummy_routing_table.s"
	@echo "... forwarder/fwd.o"
	@echo "... forwarder/fwd.i"
	@echo "... forwarder/fwd.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... router.o"
	@echo "... router.i"
	@echo "... router.s"
	@echo "... routing_table.o"
	@echo "... routing_table.i"
	@echo "... routing_table.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

